name: Model Training and Evaluation

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of training epochs'
        required: true
        default: "3"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --break-system-packages --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
          pip install --break-system-packages --no-cache-dir numpy pandas scikit-learn tqdm
      - name: Run preprocessing script
        run: cp data/*.csv ./ && python preprocess.py
      - name: Train model
        run: python train.py --epochs ${{ inputs.epochs }}
      - name: Save model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: ./model.pth
      - name: Save test split
        uses: actions/upload-artifact@v4
        with:
          name: test_split
          path: ./test_split.csv

  evaluate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --break-system-packages --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
          pip install --break-system-packages --no-cache-dir numpy pandas scikit-learn tqdm
      - name: Load model
        uses: actions/download-artifact@v4
        with:
          name: model
          path: .
      - name: Load test split
        uses: actions/download-artifact@v4
        with:
          name: test_split
          path: .
      - name: Run evaluation script
        run: python predict.py
